--- 
abstract: write tests, not scripts that run them
author: Jonathan Rockway C<< <jrockway AT cpan.org> >>.
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-TableDriven
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Dumper: 0
  Test::More: 0
version: 0.02
